---
- name: Deploy GitLab on CentOS
  include_tasks: Centos_gitlab.yaml
  when:
    - ansible_os_family == "RedHat"

- name: Deploy GitLab on Debian
  include_tasks: Debian_gitlab.yaml
  when:
    - ansible_os_family == "Debian"

